"""
Phase: Validation Phase
Validate collected configuration

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import yaml
import sys

# === GENERATED: STEP_IMPORTS - DO NOT EDIT ===
# Handle both relative imports (when called by parent) and absolute imports (when run standalone)
if __name__ == '__main__':
    # Running standalone - use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_4_validation.step_1_schema_validation.schema_validation import SchemaValidationStep
    from phases.phase_4_validation.step_2_dependency_validation.dependency_validation import DependencyValidationStep
    from phases.phase_4_validation.step_3_environment_validation.environment_validation import EnvironmentValidationStep
else:
    # When imported as module, use relative imports
    from .step_1_schema_validation.schema_validation import SchemaValidationStep
    from .step_2_dependency_validation.dependency_validation import DependencyValidationStep
    from .step_3_environment_validation.environment_validation import EnvironmentValidationStep
# === END GENERATED: STEP_IMPORTS ===

# Infrastructure imports (preserved, not regenerated)
# Add phase-specific infrastructure imports here:
# - PathResolver for artifact resolution
# - Custom utilities or helpers
# - External dependencies
#
# Example:
# try:
#     from control_flow_engine.runtime import PathResolver, PathResolutionError
# except ImportError:
#     PathResolver = None
#     PathResolutionError = Exception

logger = logging.getLogger(__name__)


class ValidationPhase:
    """
    Validation Phase
    Status: IMPLEMENTED
    
    Validate collected configuration
    
    Artifacts Consumed: user_configuration
    Artifacts Produced: validation_report
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_4_validation"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Validation Phase.
        
        Args:
            context: Execution context with consumed artifacts
            
        Returns:
            Dict with produced artifacts
        """
        if self.ui:
            self.ui.show_phase_header("Validation Phase", "Validate collected configuration")
        
        logger.info("Executing Validation Phase")
        
        result = {'artifacts': {}}
        
        # === GENERATED: STEP_EXECUTION - DO NOT EDIT ===
# Step 1: Validate configuration against schema
        logger.info("Step 1: Validate configuration against schema")
        step_1 = SchemaValidationStep(self.project_root, self.ui)
        step_result = step_1.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 2: Validate inter-service dependencies
        logger.info("Step 2: Validate inter-service dependencies")
        step_2 = DependencyValidationStep(self.project_root, self.ui)
        step_result = step_2.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 3: Validate environment-specific requirements
        logger.info("Step 3: Validate environment-specific requirements")
        step_3 = EnvironmentValidationStep(self.project_root, self.ui)
        step_result = step_3.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
# === END GENERATED: STEP_EXECUTION ===
        
        logger.info("Validation Phase completed successfully")
        
        # Return validation results from context
        return {
            'artifacts': result['artifacts'],
            'validation_report': context.get('validation_report'),
            'validated_configuration': context.get('validated_configuration')
        }


def main():
    """Standalone entry point for testing Phase 4: Validation."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Phase 4: Validation")
    parser.add_argument('--user-config', required=True, help='Path to user_configuration.yml from Phase 3')
    parser.add_argument('--output-dir', help='Output directory', default=None)
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    phase_dir = Path(__file__).parent
    project_root = phase_dir.parent.parent  # Go up 2 levels: phase_4_validation -> phases -> config-manager
    
    try:
        # Initialize phase
        phase = ValidationPhase(project_root=project_root, ui=None)
        
        # Load user configuration
        user_config_path = Path(args.user_config)
        if not user_config_path.exists():
            print(f"❌ User configuration file not found: {user_config_path}")
            return 1
        
        with open(user_config_path, 'r') as f:
            user_config = yaml.safe_load(f)
        
        # Build context
        context = {
            'user_configuration_file': str(user_config_path),
            'user_configuration': user_config
        }
        
        # Execute phase
        logger.info("Executing Validation Phase")
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        if result.get('validation_passed', False):
            print("✅ PHASE 4 COMPLETE: Validation PASSED")
        else:
            print("⚠️  PHASE 4 COMPLETE: Validation FAILED")
        print("=" * 70)
        print(f"\n📊 Phase Summary:")
        print(f"  • validation_report_file: {result.get('validation_report_file', 'N/A')}")
        print(f"  • validation_passed: {result.get('validation_passed', False)}")
        
        if result.get('validation_passed', False):
            print(f"\n✅ Ready for Phase 5: Export")
        else:
            print(f"\n❌ Please fix validation errors before proceeding")
        
        return 0 if result.get('validation_passed', False) else 1
        
    except Exception as e:
        print(f"\n❌ Phase 4 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
