"""
Phase: Validation Phase
Validate collected configuration

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import yaml
import sys

# Conditional imports to handle both module context and standalone execution
if __name__ == '__main__':
    # When running as standalone script, add parent to path and use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_4_validation.step_1_schema_validation import schema_validation
    from phases.phase_4_validation.step_2_dependency_validation import dependency_validation
    from phases.phase_4_validation.step_3_environment_validation import environment_validation
else:
    # When imported as module, use relative imports
    from .step_1_schema_validation import schema_validation
    from .step_2_dependency_validation import dependency_validation
    from .step_3_environment_validation import environment_validation

logger = logging.getLogger(__name__)


class ValidationPhase:
    """
    Validation Phase
    Status: IMPLEMENTED
    
    Validate collected configuration
    
    Artifacts Consumed: user_configuration
    Artifacts Produced: validation_report
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_4_validation"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Validation Phase.
        
        Args:
            context: Execution context with consumed artifacts
            
        Returns:
            Dict with produced artifacts
        """
        if self.ui:
            self.ui.show_phase_header("Validation Phase", "Validate collected configuration")
        
        logger.info("Executing Validation Phase")
        
        # Execute validation steps
        schema_result = schema_validation.execute_schema_validation(context, self.phase_dir)
        dependency_result = dependency_validation.execute_dependency_validation(context, self.phase_dir)
        environment_result = environment_validation.execute_environment_validation(context, self.phase_dir)
        
        # Aggregate results
        all_passed = (
            schema_result.get('passed', False) and
            dependency_result.get('passed', False) and
            environment_result.get('passed', False)
        )
        
        # Collect all issues
        all_errors = schema_result.get('errors', [])
        all_warnings = (
            schema_result.get('warnings', []) +
            dependency_result.get('warnings', []) +
            environment_result.get('warnings', [])
        )
        all_recommendations = (
            dependency_result.get('recommendations', []) +
            environment_result.get('recommendations', [])
        )
        
        # Generate validation report
        validation_report = {
            'validation_status': 'PASSED' if all_passed else 'FAILED',
            'schema_validation': schema_result,
            'dependency_validation': dependency_result,
            'environment_validation': environment_result,
            'summary': {
                'total_errors': len(all_errors),
                'total_warnings': len(all_warnings),
                'total_recommendations': len(all_recommendations),
                'passed': all_passed
            }
        }
        
        # Write validation report to output
        outputs_dir = self.project_root / "phases/outputs"
        outputs_dir.mkdir(parents=True, exist_ok=True)
        
        report_file = outputs_dir / "validation_report.yml"
        with open(report_file, 'w') as f:
            yaml.dump(validation_report, f, default_flow_style=False, sort_keys=False)
        
        logger.info(f"Validation Phase completed: {'PASSED' if all_passed else 'FAILED'}")
        logger.info(f"Validation report written to {report_file}")
        
        if not all_passed:
            logger.error(f"Validation failed with {len(all_errors)} errors")
            for error in all_errors:
                logger.error(f"  - {error}")
        
        return {
            'validation_report_file': str(report_file),
            'validation_passed': all_passed
        }


def main():
    """Standalone entry point for testing Phase 4: Validation."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Phase 4: Validation")
    parser.add_argument('--user-config', required=True, help='Path to user_configuration.yml from Phase 3')
    parser.add_argument('--output-dir', help='Output directory', default=None)
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    phase_dir = Path(__file__).parent
    project_root = phase_dir.parent.parent  # Go up 2 levels: phase_4_validation -> phases -> config-manager
    
    try:
        # Initialize phase
        phase = ValidationPhase(project_root=project_root, ui=None)
        
        # Load user configuration
        user_config_path = Path(args.user_config)
        if not user_config_path.exists():
            print(f"❌ User configuration file not found: {user_config_path}")
            return 1
        
        with open(user_config_path, 'r') as f:
            user_config = yaml.safe_load(f)
        
        # Build context
        context = {
            'user_configuration_file': str(user_config_path),
            'user_configuration': user_config
        }
        
        # Execute phase
        logger.info("Executing Validation Phase")
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        if result.get('validation_passed', False):
            print("✅ PHASE 4 COMPLETE: Validation PASSED")
        else:
            print("⚠️  PHASE 4 COMPLETE: Validation FAILED")
        print("=" * 70)
        print(f"\n📊 Phase Summary:")
        print(f"  • validation_report_file: {result.get('validation_report_file', 'N/A')}")
        print(f"  • validation_passed: {result.get('validation_passed', False)}")
        
        if result.get('validation_passed', False):
            print(f"\n✅ Ready for Phase 5: Export")
        else:
            print(f"\n❌ Please fix validation errors before proceeding")
        
        return 0 if result.get('validation_passed', False) else 1
        
    except Exception as e:
        print(f"\n❌ Phase 4 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
