"""
Phase: Export Phase
Export final configuration files for deployment

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import yaml
import sys

# Conditional imports - no step modules to import for this phase
if __name__ == '__main__':
    # When running as standalone script, add parent to path
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))

logger = logging.getLogger(__name__)


class ExportPhase:
    """
    Export Phase
    Status: IMPLEMENTED
    
    Export final configuration files for deploy-manager consumption
    
    Artifacts Consumed: validated_configuration
    Artifacts Produced: final_configuration_files (docker-compose.yml, .env, manifest)
    
    Note: Outputs to phases/outputs/ directory for deploy-manager
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_5_export"
        # Output to top-level phases/outputs/ for deploy-manager
        self.export_dir = project_root / "phases/outputs"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Export Phase.
        
        Args:
            context: Execution context with validated_configuration
            
        Returns:
            Dict with produced artifacts:
                - docker_compose_file: Path to docker-compose.yml
                - env_file: Path to .env file
                - manifest_file: Path to configuration manifest
        """
        if self.ui:
            self.ui.show_phase_header("Export Phase", "Export final configuration files for deployment")
        
        logger.info("Executing Export Phase")
        
        # Create export directory
        self.export_dir.mkdir(parents=True, exist_ok=True)
        
        # Check validation result
        validation_passed = context.get('validation_passed', False)
        if not validation_passed:
            logger.warning("⚠️  Configuration validation had errors - proceeding with caution")
            logger.warning("Check validation_report.yml for details")
        
        # Load validated configuration from Phase 3
        user_config_file = context.get('user_configuration_file')
        if not user_config_file:
            raise ValueError("user_configuration_file not found in context")
        
        with open(user_config_file, 'r') as f:
            raw_config = yaml.safe_load(f)
        
        # Extract user_responses and convert from dot notation to nested dict
        user_responses = raw_config.get('user_responses', {})
        user_config = self._convert_dot_notation_to_nested(user_responses)
        
        validated_config = context.get('validated_configuration', user_config)
        
        # Export docker-compose.yml
        docker_compose_file = self._export_docker_compose(validated_config, user_config)
        logger.info(f"Exported docker-compose.yml to {docker_compose_file}")
        
        # Export .env file
        env_file = self._export_env_file(validated_config, user_config)
        logger.info(f"Exported .env file to {env_file}")
        
        # Export configuration manifest
        manifest_file = self._export_manifest(context)
        logger.info(f"Exported manifest to {manifest_file}")
        
        logger.info(f"Export Phase completed - Files written to {self.export_dir}")
        
        export_summary = {
            'files_exported': 3,
            'export_directory': str(self.export_dir),
            'files': [
                str(docker_compose_file),
                str(env_file),
                str(manifest_file)
            ]
        }
        
        return {
            'docker_compose_file': str(docker_compose_file),
            'env_file': str(env_file),
            'manifest_file': str(manifest_file),
            'export_summary': export_summary,
            'final_configuration_files': str(self.export_dir)
        }
    
    def _export_docker_compose(self, validated_config: Dict[str, Any], 
                               user_config: Dict[str, Any]) -> Path:
        """
        Export docker-compose.yml file based on validated configuration.
        """
        output_file = self.export_dir / 'docker-compose.yml'
        
        # Extract configuration sections
        project = user_config.get('project', {})
        admin = user_config.get('admin', {})
        database = user_config.get('database', {})
        email = user_config.get('email', {})
        network = user_config.get('network', {})
        storage = user_config.get('storage', {})
        
        # Build docker-compose structure
        docker_compose = {
            'version': '3.8',
            'services': {
                'openproject': {
                    'image': 'openproject/community:latest',
                    'container_name': project.get('identifier', 'openproject'),
                    'ports': [f"{network.get('port', 80)}:8080"],
                    'environment': {
                        'OPENPROJECT_HOST__NAME': network.get('domain', 'openproject.local'),
                        'OPENPROJECT_HTTPS': str(network.get('ssl_enabled', False)).lower(),
                        'OPENPROJECT_DEFAULT__LANGUAGE': project.get('language', 'en'),
                        'DATABASE_URL': f"postgres://{database.get('username', 'openproject')}:{database.get('password', 'password')}@db:5432/{database.get('database_name', 'openproject')}"
                    },
                    'volumes': [
                        'openproject-data:/var/openproject/assets'
                    ],
                    'depends_on': ['db'],
                    'restart': 'unless-stopped'
                },
                'db': {
                    'image': 'postgres:13',
                    'container_name': f"{project.get('identifier', 'openproject')}-db",
                    'environment': {
                        'POSTGRES_DB': database.get('database_name', 'openproject'),
                        'POSTGRES_USER': database.get('username', 'openproject'),
                        'POSTGRES_PASSWORD': database.get('password', 'password')
                    },
                    'volumes': [
                        'postgres-data:/var/lib/postgresql/data'
                    ],
                    'restart': 'unless-stopped'
                }
            },
            'volumes': {
                'openproject-data': {},
                'postgres-data': {}
            },
            'networks': {
                'default': {
                    'name': f"{project.get('identifier', 'openproject')}-network"
                }
            }
        }
        
        # Add email service if configured
        if email.get('enabled'):
            docker_compose['services']['mailhog'] = {
                'image': 'mailhog/mailhog',
                'container_name': f"{project.get('identifier', 'openproject')}-mail",
                'ports': ['8025:8025', '1025:1025'],
                'restart': 'unless-stopped'
            }
        
        with open(output_file, 'w') as f:
            yaml.dump(docker_compose, f, default_flow_style=False, sort_keys=False)
        
        return output_file
    
    def _export_env_file(self, validated_config: Dict[str, Any],
                        user_config: Dict[str, Any]) -> Path:
        """
        Export .env file with environment variables.
        """
        output_file = self.export_dir / '.env'
        
        # Extract configuration sections
        project = user_config.get('project', {})
        admin = user_config.get('admin', {})
        database = user_config.get('database', {})
        email = user_config.get('email', {})
        network = user_config.get('network', {})
        storage = user_config.get('storage', {})
        
        # Build environment variables
        env_vars = {
            '# OpenProject Configuration': '',
            '# Generated by config-manager': '',
            '': '',
            '# Project Settings': '',
            'PROJECT_NAME': project.get('name', 'OpenProject'),
            'PROJECT_IDENTIFIER': project.get('identifier', 'openproject'),
            'PROJECT_LANGUAGE': project.get('language', 'en'),
            '# Admin User': '',
            'ADMIN_EMAIL': admin.get('email', 'admin@example.com'),
            'ADMIN_FIRST_NAME': admin.get('first_name', 'Admin'),
            'ADMIN_LAST_NAME': admin.get('last_name', 'User'),
            '# Network Settings': '',
            'OPENPROJECT_HOST__NAME': network.get('domain', 'openproject.local'),
            'OPENPROJECT_HTTPS': str(network.get('ssl_enabled', False)).lower(),
            'OPENPROJECT_PORT': str(network.get('port', 80)),
            '# Database Configuration': '',
            'POSTGRES_DB': database.get('database_name', 'openproject'),
            'POSTGRES_USER': database.get('username', 'openproject'),
            'POSTGRES_PASSWORD': database.get('password', 'password'),
            'DATABASE_URL': f"postgres://{database.get('username', 'openproject')}:{database.get('password', 'password')}@db:5432/{database.get('database_name', 'openproject')}"
        }
        
        # Add email settings if configured
        if email.get('enabled'):
            env_vars.update({
                '# Email Configuration': '',
                'EMAIL_DELIVERY_METHOD': email.get('smtp_server', 'smtp') if email.get('smtp_server') else 'mailhog',
                'SMTP_ADDRESS': email.get('smtp_server', 'mailhog'),
                'SMTP_PORT': str(email.get('smtp_port', 1025)),
                'SMTP_DOMAIN': network.get('domain', 'openproject.local'),
                'SMTP_USERNAME': email.get('smtp_username', ''),
                'SMTP_PASSWORD': email.get('smtp_password', '')
            })
        
        with open(output_file, 'w') as f:
            for key, value in env_vars.items():
                if key.startswith('#') or key == '':
                    f.write(f"{key}\n")
                else:
                    f.write(f"{key}={value}\n")
        
        return output_file
    
    def _convert_dot_notation_to_nested(self, dot_dict: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert flat dot notation dict to nested dict.
        Example: {'project.name': 'Test'} -> {'project': {'name': 'Test'}}
        """
        result = {}
        for key, value in dot_dict.items():
            parts = key.split('.')
            current = result
            for part in parts[:-1]:
                if part not in current:
                    current[part] = {}
                current = current[part]
            current[parts[-1]] = value
        return result
    
    def _export_manifest(self, context: Dict[str, Any]) -> Path:
        """
        Export configuration manifest for deploy-manager.
        """
        output_file = self.export_dir / 'configuration_manifest.yml'
        
        manifest = {
            'component': 'config-manager',
            'version': '1.0.0',
            'generated_at': context.get('generated_at', 'unknown'),
            'pipeline_status': 'complete',
            'phases_completed': [
                'discovery',
                'tui_mapping',
                'collection',
                'validation',
                'export'
            ],
            'artifacts': {
                'docker_compose': 'docker-compose.yml',
                'environment': '.env',
                'manifest': 'configuration_manifest.yml'
            },
            'ready_for_deployment': True,
            'metadata': {
                'discovery_summary': context.get('discovery_summary', {}),
                'validation_status': context.get('validation_passed', False)
            }
        }
        
        with open(output_file, 'w') as f:
            yaml.dump(manifest, f, default_flow_style=False, sort_keys=False)
        
        return output_file


def main():
    """Standalone entry point for testing Phase 5: Export."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Phase 5: Export")
    parser.add_argument('--user-config', required=True, help='Path to user_configuration.yml from Phase 3')
    parser.add_argument('--validation-passed', action='store_true', help='Set if validation passed')
    parser.add_argument('--output-dir', help='Output directory', default=None)
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    phase_dir = Path(__file__).parent
    project_root = phase_dir.parent.parent  # Go up 2 levels: phase_5_export -> phases -> config-manager
    
    try:
        # Initialize phase
        phase = ExportPhase(project_root=project_root, ui=None)
        
        # Load user configuration
        user_config_path = Path(args.user_config)
        if not user_config_path.exists():
            print(f"❌ User configuration file not found: {user_config_path}")
            return 1
        
        # Build context
        context = {
            'user_configuration_file': str(user_config_path),
            'validation_passed': args.validation_passed
        }
        
        # Execute phase
        logger.info("Executing Export Phase")
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        print("✅ PHASE 5 COMPLETE: Export")
        print("=" * 70)
        print(f"\n📊 Phase Summary:")
        
        if 'export_summary' in result:
            summary = result['export_summary']
            print(f"  • Files exported: {summary.get('files_exported', 0)}")
            print(f"  • Export directory: {summary.get('export_directory', 'N/A')}")
            print(f"\n📁 Exported files:")
            for file in summary.get('files', []):
                print(f"    - {Path(file).name}")
        
        print(f"\n✅ Configuration ready for deployment!")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Phase 5 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
