"""
Phase: Export Phase
Export final configuration files for deployment

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import yaml
import sys

# === GENERATED: STEP_IMPORTS - DO NOT EDIT ===
# Handle both relative imports (when called by parent) and absolute imports (when run standalone)
if __name__ == '__main__':
    # Running standalone - use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_5_export.step_1_export_docker_compose.export_docker_compose import ExportDockerComposeStep
    from phases.phase_5_export.step_2_export_env_file.export_env_file import ExportEnvFileStep
    from phases.phase_5_export.step_3_export_manifest.export_manifest import ExportManifestStep
else:
    # When imported as module, use relative imports
    from .step_1_export_docker_compose.export_docker_compose import ExportDockerComposeStep
    from .step_2_export_env_file.export_env_file import ExportEnvFileStep
    from .step_3_export_manifest.export_manifest import ExportManifestStep
# === END GENERATED: STEP_IMPORTS ===

# Infrastructure imports (preserved, not regenerated)
# Add phase-specific infrastructure imports here:
# - PathResolver for artifact resolution
# - Custom utilities or helpers
# - External dependencies
#
# Example:
# try:
#     from control_flow_engine.runtime import PathResolver, PathResolutionError
# except ImportError:
#     PathResolver = None
#     PathResolutionError = Exception

logger = logging.getLogger(__name__)


class ExportPhase:
    """
    Export Phase
    Status: IMPLEMENTED
    
    Export final configuration files for deployment
    
    Artifacts Consumed: validated_configuration
    Artifacts Produced: docker_compose_file, env_file, manifest_file
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_5_export"
        # Output to top-level phases/outputs/ for deploy-manager
        self.export_dir = project_root / "phases/outputs"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Export Phase.
        
        Args:
            context: Execution context with validated_configuration
            
        Returns:
            Dict with produced artifacts
        """
        if self.ui:
            self.ui.show_phase_header("Export Phase", "Export final configuration files for deployment")
        
        logger.info("Executing Export Phase")
        
        # Create export directory
        self.export_dir.mkdir(parents=True, exist_ok=True)
        
        # Add export_dir to context for steps to use
        context['export_dir'] = str(self.export_dir)
        
        # Check validation result
        validation_passed = context.get('validation_passed', False)
        if not validation_passed:
            logger.warning("⚠️  Configuration validation had errors - proceeding with caution")
            logger.warning("Check validation_report.yml for details")
        
        # Load user configuration if it's a file path
        user_config_file = context.get('user_configuration_file')
        if user_config_file and isinstance(user_config_file, str):
            user_config_path = Path(user_config_file)
            if user_config_path.exists():
                with open(user_config_path, 'r') as f:
                    raw_config = yaml.safe_load(f)
                
                # Extract user_responses and convert from dot notation to nested dict
                user_responses = raw_config.get('user_responses', {})
                user_config = self._convert_dot_notation_to_nested(user_responses)
                context['user_configuration'] = user_config
        
        result = {'artifacts': {}}
        
        # === GENERATED: STEP_EXECUTION - DO NOT EDIT ===
# Step 1: Export docker-compose.yml file for deployment
        logger.info("Step 1: Export docker-compose.yml file for deployment")
        step_1 = ExportDockerComposeStep(self.project_root, self.ui)
        step_result = step_1.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 2: Export .env file with environment variables
        logger.info("Step 2: Export .env file with environment variables")
        step_2 = ExportEnvFileStep(self.project_root, self.ui)
        step_result = step_2.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 3: Export configuration manifest for deploy-manager
        logger.info("Step 3: Export configuration manifest for deploy-manager")
        step_3 = ExportManifestStep(self.project_root, self.ui)
        step_result = step_3.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
# === END GENERATED: STEP_EXECUTION ===
        
        logger.info("Export Phase completed successfully")
        logger.info(f"Files written to {self.export_dir}")
        
        # Return collected artifacts from context
        return {
            'artifacts': result['artifacts'],
            'docker_compose_file': context.get('docker_compose_file'),
            'env_file': context.get('env_file'),
            'manifest_file': context.get('manifest_file'),
            'export_summary': context.get('export_summary'),
            'final_configuration_files': str(self.export_dir)
        }
    
    def _convert_dot_notation_to_nested(self, dot_dict: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert flat dot notation dict to nested dict.
        Example: {'project.name': 'Test'} -> {'project': {'name': 'Test'}}
        """
        result = {}
        for key, value in dot_dict.items():
            parts = key.split('.')
            current = result
            for part in parts[:-1]:
                if part not in current:
                    current[part] = {}
                current = current[part]
            current[parts[-1]] = value
        return result


def main():
    """Standalone entry point for testing Phase 5: Export."""
    import argparse
    from datetime import datetime
    
    parser = argparse.ArgumentParser(description="Phase 5: Export")
    parser.add_argument('--user-config', required=True, help='Path to user_configuration.yml from Phase 3')
    parser.add_argument('--validation-passed', action='store_true', help='Set if validation passed')
    parser.add_argument('--output-dir', help='Output directory', default=None)
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    phase_dir = Path(__file__).parent
    project_root = phase_dir.parent.parent
    
    try:
        # Initialize phase
        phase = ExportPhase(project_root=project_root, ui=None)
        
        # Build context
        context = {
            'user_configuration_file': args.user_config,
            'validation_passed': args.validation_passed,
            'generated_at': datetime.now().isoformat()
        }
        
        if args.output_dir:
            context['export_dir'] = args.output_dir
        
        # Execute export
        result = phase.execute(context)
        
        print(f"\n✅ Export Phase completed!")
        print(f"📁 Files exported:")
        print(f"  - {result.get('docker_compose_file')}")
        print(f"  - {result.get('env_file')}")
        print(f"  - {result.get('manifest_file')}")
        print(f"\n✅ Ready for deployment!")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Export phase failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    exit(main())
