"""
Phase: Interactive Collection
Collect user configuration via interactive UI

Generated by Control Flow Engine
"""

import os
from pathlib import Path
from typing import Dict, Any
import logging
import sys

# =============================================================================
# PATH CONFIGURATION
# =============================================================================
# These constants define the phase's location in the project structure.
# They work together with PathResolver to ensure consistent path resolution.

# PHASE_SEQUENCE: Physical position in phases directory (changeable during reordering)
# Override via environment: export PHASE_SEQUENCE=N
PHASE_SEQUENCE = int(os.getenv('PHASE_SEQUENCE', '3'))

# PHASE_ID: Logical identifier (stable, never changes)
PHASE_ID = 'collection'

# Computed paths (automatically adjusted when PHASE_SEQUENCE changes)
PHASE_DIR_NAME = f"phase_{PHASE_SEQUENCE}_{PHASE_ID}"

# PROJECT_ROOT: Auto-detected or override via environment
# Override via environment: export PROJECT_ROOT=/path/to/project
PROJECT_ROOT = Path(os.getenv('PROJECT_ROOT', Path(__file__).parent.parent.parent)).resolve()

# PHASE_DIR: Full path to this phase's directory
PHASE_DIR = PROJECT_ROOT / "phases" / PHASE_DIR_NAME

# OUTPUT_DIR: Where this phase writes its artifacts
OUTPUT_DIR = PHASE_DIR / "outputs"

# =============================================================================

# === GENERATED: STEP_IMPORTS - DO NOT EDIT ===
# Handle both relative imports (when called by parent) and absolute imports (when run standalone)
if __name__ == '__main__':
    # Running standalone - use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_3_collection.step_1_collect_user_configuration.collect_user_configuration import CollectUserConfigurationStep
else:
    # When imported as module, use relative imports
    from .step_1_collect_user_configuration.collect_user_configuration import CollectUserConfigurationStep
# === END GENERATED: STEP_IMPORTS ===

# Infrastructure imports (not generated)
try:
    from control_flow_engine.runtime import PathResolver, PathResolutionError
except ImportError:
    PathResolver = None
    PathResolutionError = Exception

logger = logging.getLogger(__name__)


class CollectionPhase:
    """
    Interactive Collection
    Status: IMPLEMENTED
    
    Collect user configuration via interactive UI
    
    Artifacts Consumed: tui_defaults_file
    Artifacts Produced: user_configuration
    """
    
    def __init__(self, project_root: Path = None, ui=None, path_resolver=None):
        # Use path constants if no project_root provided
        self.project_root = project_root if project_root else PROJECT_ROOT
        self.ui = ui
        self.phase_dir = PHASE_DIR
        
        # Initialize path resolver for artifact resolution
        if path_resolver:
            self.path_resolver = path_resolver
        elif PathResolver:
            try:
                self.path_resolver = PathResolver.from_execution_context(__file__)
            except Exception as e:
                logger.warning(f"Could not initialize PathResolver: {e}")
                self.path_resolver = None
        else:
            self.path_resolver = None
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Interactive Collection.
        
        Args:
            context: Execution context with consumed artifacts:
                - tui_defaults_file: Path to Phase 2 TUI defaults (optional)
                - mock_responses: Optional mock responses for testing
                - flow_name: Optional flow name (default: config_tui.layout)
            
        Returns:
            Dict with produced artifacts:
                - user_configuration: Path to collected configuration YAML
        """
        if self.ui:
            self.ui.show_phase_header("Interactive Collection", "Collect user configuration via interactive UI")
        
        logger.info("Executing Interactive Collection")
        
        result = {'artifacts': {}}
        
        # === GENERATED: STEP_EXECUTION - DO NOT EDIT ===
# Step 1: Load TUI layout and defaults, render interactive form, collect user input
        logger.info("Step 1: Load TUI layout and defaults, render interactive form, collect user input")
        step_1 = CollectUserConfigurationStep(self.project_root, self.ui)
        step_result = step_1.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
# === END GENERATED: STEP_EXECUTION ===
        
        logger.info("Interactive Collection completed successfully")
        
        # Return collected artifacts from context
        return {
            'artifacts': result['artifacts'],
            'user_configuration_file': context.get('user_configuration_file'),
            'user_configuration': context.get('user_configuration')
        }


def main():
    """Standalone entry point for testing Phase 3: Interactive Collection."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Phase 3: Interactive Collection")
    parser.add_argument('--tui-defaults', help='Path to tui_defaults.yml from Phase 2 (optional)')
    parser.add_argument('--mock-file', help='Path to mock responses file (optional)')
    parser.add_argument('--output-dir', help='Output directory', default=None)
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    parser.add_argument('--show-paths', action='store_true', help='Display path configuration and exit')
    
    args = parser.parse_args()
    
    # Show path configuration if requested
    if args.show_paths:
        print("\n" + "=" * 70)
        print("PATH CONFIGURATION")
        print("=" * 70)
        print(f"\n📍 Phase Identity:")
        print(f"   PHASE_SEQUENCE: {PHASE_SEQUENCE}")
        print(f"   PHASE_ID: {PHASE_ID}")
        print(f"   PHASE_DIR_NAME: {PHASE_DIR_NAME}")
        print(f"\n📂 Computed Paths:")
        print(f"   PROJECT_ROOT: {PROJECT_ROOT}")
        print(f"   PHASE_DIR: {PHASE_DIR}")
        print(f"   OUTPUT_DIR: {OUTPUT_DIR}")
        
        # Validate against PathResolver
        if PathResolver:
            try:
                path_resolver = PathResolver.from_execution_context(__file__)
                resolver_phase_dir = path_resolver.resolve_phase_directory(PHASE_ID)
                resolver_output_dir = path_resolver.resolve_phase_output_dir(PHASE_ID)
                
                print(f"\n✅ PathResolver Validation:")
                
                if Path(resolver_phase_dir) == PHASE_DIR:
                    print(f"   Phase directory: MATCHES")
                else:
                    print(f"   Phase directory: MISMATCH")
                    print(f"     Computed: {PHASE_DIR}")
                    print(f"     Resolver: {resolver_phase_dir}")
                
                if Path(resolver_output_dir) == OUTPUT_DIR:
                    print(f"   Output directory: MATCHES")
                else:
                    print(f"   Output directory: MISMATCH")
                    print(f"     Computed: {OUTPUT_DIR}")
                    print(f"     Resolver: {resolver_output_dir}")
            except Exception as e:
                print(f"\n⚠️  PathResolver validation failed: {e}")
        else:
            print(f"\n⚠️  PathResolver not available")
        
        print("\n" + "=" * 70)
        return 0
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    try:
        # Initialize phase with path resolver
        path_resolver = PathResolver.from_execution_context(__file__) if PathResolver else None
        phase = CollectionPhase(project_root=PROJECT_ROOT, ui=None, path_resolver=path_resolver)
        
        # Build context
        context = {}
        if args.tui_defaults:
            context['tui_defaults_file'] = args.tui_defaults
        if args.mock_file:
            context['mock_responses'] = args.mock_file
        
        # Execute phase
        logger.info("Executing Interactive Collection Phase")
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        print("✅ PHASE 3 COMPLETE: Interactive Collection")
        print("=" * 70)
        print(f"\n📊 Phase Summary:")
        print(f"  • user_configuration_file: {result.get('user_configuration_file', 'N/A')}")
        
        print(f"\n✅ Ready for Phase 4: Validation")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Phase 3 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
