"""Configuration file writer for .cfg format export."""

import os
import logging
from typing import Union, Optional
from pathlib import Path
from datetime import datetime
import shutil

from src.openproject_config_manager.core.config import Configuration


logger = logging.getLogger(__name__)


class CfgWriter:
    """Writer for OpenProject configuration files in .cfg format."""
    
    def __init__(self):
        """Initialize the configuration writer."""
        pass
    
    def write_configuration(self, 
                          configuration: Configuration,
                          output_path: Union[str, Path],
                          backup_existing: bool = True,
                          add_comments: bool = True) -> str:
        """
        Write configuration to .cfg file format.
        
        Args:
            configuration: Configuration object to export
            output_path: Path to write the configuration file
            backup_existing: Whether to backup existing file
            add_comments: Whether to add explanatory comments
            
        Returns:
            Path to the written configuration file
        """
        output_path = Path(output_path)
        
        logger.info(f"Writing configuration to {output_path}")
        
        # Create directory if it doesn't exist
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Backup existing file if requested
        if backup_existing and output_path.exists():
            self._backup_existing_file(output_path)
        
        # Generate configuration content
        if add_comments:
            config_content = self._generate_cfg_with_comments(configuration)
        else:
            config_content = configuration.to_cfg_format()
        
        # Write to file
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(config_content)
            
            logger.info(f"Configuration successfully written to {output_path}")
            
            # Set appropriate file permissions (readable by owner/group, not world)
            os.chmod(output_path, 0o640)
            
            return str(output_path)
            
        except Exception as e:
            logger.error(f"Failed to write configuration file: {e}")
            raise
    
    def _backup_existing_file(self, file_path: Path):
        """Create a backup of existing configuration file."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = file_path.with_suffix(f".{timestamp}.bak")
        
        try:
            shutil.copy2(file_path, backup_path)
            logger.info(f"Existing file backed up to {backup_path}")
        except Exception as e:
            logger.warning(f"Failed to backup existing file: {e}")
    
    def _generate_cfg_with_comments(self, configuration: Configuration) -> str:
        """Generate .cfg file with detailed comments and explanations."""
        lines = []
        
        # Header
        lines.extend([
            "# OpenProject Configuration File",
            "# Generated by OpenProject Configuration Manager",
            f"# Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "#",
            "# This file contains the configuration for your OpenProject deployment.",
            "# It will be used by the deployment manager to set up your OpenProject instance.",
            "#",
            "# IMPORTANT: This file contains sensitive information including passwords",
            "# and secret keys. Keep it secure and do not commit to version control.",
            "",
        ])
        
        # Core OpenProject Settings
        lines.extend([
            "# =============================================================================",
            "# CORE OPENPROJECT SETTINGS", 
            "# =============================================================================",
            "#",
            "# SECRET_KEY_BASE: Used for encrypting session data and other sensitive information",
            "# This should be a long, random string. Never share this value.",
            f'SECRET_KEY_BASE="{configuration.secret_key_base}"',
            "",
            "# RAILS_ENV: The Rails environment (production, development)",
            "# Use 'production' for live deployments, 'development' for testing only",
            f'RAILS_ENV="{configuration.rails_env}"',
            "",
            "# RAILS_CACHE_STORE: Caching backend for improved performance",
            "# Options: memcache, redis, file_store",
            f'RAILS_CACHE_STORE="{configuration.rails_cache_store}"',
            "",
        ])
        
        # Database Configuration
        lines.extend([
            "# =============================================================================",
            "# DATABASE CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Database connection settings for OpenProject data storage",
            "#",
            "# DATABASE_ADAPTER: Database type (postgresql recommended, mysql also supported)",
            f'DATABASE_ADAPTER="{configuration.database.adapter}"',
            "",
            "# DATABASE_HOST: Database server hostname or container name",
            f'DATABASE_HOST="{configuration.database.host}"',
            "",
            "# DATABASE_PORT: Database server port",
            f'DATABASE_PORT="{configuration.database.port}"',
            "",
            "# DATABASE_NAME: Name of the OpenProject database",
            f'DATABASE_NAME="{configuration.database.name}"',
            "",
            "# DATABASE_USERNAME: Database user for OpenProject",
            f'DATABASE_USERNAME="{configuration.database.username}"',
            "",
            "# DATABASE_PASSWORD: Database password (keep secure!)",
            f'DATABASE_PASSWORD="{configuration.database.password}"',
            "",
            "# DATABASE_ENCODING: Character encoding for the database",
            f'DATABASE_ENCODING="{configuration.database.encoding}"',
            "",
        ])
        
        # Proxy and Security Configuration
        lines.extend([
            "# =============================================================================",
            "# PROXY AND SECURITY CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Domain and SSL settings for external access",
            "#",
            "# DOMAIN: Primary domain name for your OpenProject instance",
            f'DOMAIN="{configuration.proxy.domain}"',
            "",
        ])
        
        if configuration.proxy.additional_domains:
            lines.extend([
                "# ADDITIONAL_DOMAINS: Comma-separated list of additional domains",
                f'ADDITIONAL_DOMAINS="{",".join(configuration.proxy.additional_domains)}"',
                "",
            ])
        
        lines.extend([
            "# SSL_ENABLED: Enable HTTPS encryption (strongly recommended)",
            f'SSL_ENABLED="{str(configuration.proxy.ssl_enabled).lower()}"',
            "",
        ])
        
        if configuration.proxy.ssl_enabled:
            if configuration.proxy.lets_encrypt:
                lines.extend([
                    "# LETS_ENCRYPT: Use Let's Encrypt for automatic SSL certificates",
                    f'LETS_ENCRYPT="{str(configuration.proxy.lets_encrypt).lower()}"',
                    "",
                    "# LETS_ENCRYPT_EMAIL: Email for Let's Encrypt notifications",
                    f'LETS_ENCRYPT_EMAIL="{configuration.proxy.lets_encrypt_email}"',
                    "",
                ])
            else:
                if configuration.proxy.ssl_cert_path:
                    lines.extend([
                        "# SSL_CERT_PATH: Path to SSL certificate file",
                        f'SSL_CERT_PATH="{configuration.proxy.ssl_cert_path}"',
                        "",
                    ])
                if configuration.proxy.ssl_key_path:
                    lines.extend([
                        "# SSL_KEY_PATH: Path to SSL private key file",
                        f'SSL_KEY_PATH="{configuration.proxy.ssl_key_path}"',
                        "",
                    ])
        
        # Storage Configuration
        lines.extend([
            "# =============================================================================",
            "# STORAGE AND BACKUP CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Data persistence and backup settings",
            "#",
            "# DATA_VOLUME: Docker volume name for application data",
            f'DATA_VOLUME="{configuration.storage.data_volume}"',
            "",
            "# LOGS_VOLUME: Docker volume name for application logs", 
            f'LOGS_VOLUME="{configuration.storage.logs_volume}"',
            "",
            "# BACKUP_ENABLED: Enable automated backups",
            f'BACKUP_ENABLED="{str(configuration.storage.backup_enabled).lower()}"',
            "",
        ])
        
        if configuration.storage.backup_enabled:
            lines.extend([
                "# BACKUP_SCHEDULE: Backup schedule in cron format (default: daily at 2 AM)",
                f'BACKUP_SCHEDULE="{configuration.storage.backup_schedule}"',
                "",
                "# BACKUP_RETENTION_DAYS: Number of days to keep backup files",
                f'BACKUP_RETENTION_DAYS="{configuration.storage.backup_retention_days}"',
                "",
                "# BACKUP_LOCATION: Directory for storing backup files",
                f'BACKUP_LOCATION="{configuration.storage.backup_location}"',
                "",
            ])
        
        # Email Configuration
        lines.extend([
            "# =============================================================================",
            "# EMAIL CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Email delivery settings for notifications and user communication",
            "#",
            "# EMAIL_DELIVERY_METHOD: Method for sending emails",
            "# Options: smtp (recommended), sendmail, letter_opener (development only)",
            f'EMAIL_DELIVERY_METHOD="{configuration.email_delivery_method}"',
            "",
        ])
        
        if configuration.email_delivery_method == 'smtp':
            lines.extend([
                "# SMTP server configuration",
                "#",
                "# SMTP_ADDRESS: SMTP server hostname",
                f'SMTP_ADDRESS="{configuration.smtp_address}"',
                "",
                "# SMTP_PORT: SMTP server port (587 for STARTTLS, 465 for SSL, 25 for plain)",
                f'SMTP_PORT="{configuration.smtp_port}"',
                "",
            ])
            
            if configuration.smtp_domain:
                lines.extend([
                    "# SMTP_DOMAIN: SMTP HELO domain",
                    f'SMTP_DOMAIN="{configuration.smtp_domain}"',
                    "",
                ])
            
            if configuration.smtp_user_name:
                lines.extend([
                    "# SMTP_USER_NAME: SMTP authentication username",
                    f'SMTP_USER_NAME="{configuration.smtp_user_name}"',
                    "",
                ])
            
            if configuration.smtp_password:
                lines.extend([
                    "# SMTP_PASSWORD: SMTP authentication password (keep secure!)",
                    f'SMTP_PASSWORD="{configuration.smtp_password}"',
                    "",
                ])
            
            lines.extend([
                "# SMTP_ENABLE_STARTTLS_AUTO: Enable STARTTLS encryption",
                f'SMTP_ENABLE_STARTTLS_AUTO="{str(configuration.smtp_enable_starttls_auto).lower()}"',
                "",
            ])
        
        # Cache Configuration
        lines.extend([
            "# =============================================================================",
            "# CACHE CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Caching settings for improved performance",
            "#",
        ])
        
        if configuration.rails_cache_store == 'memcache':
            lines.extend([
                "# MEMCACHED_SERVER: Memcached server address",
                f'MEMCACHED_SERVER="{configuration.memcached_server}"',
                "",
            ])
        elif configuration.rails_cache_store == 'redis':
            lines.extend([
                "# REDIS_URL: Redis server URL for caching",
                f'REDIS_URL="{configuration.redis_url}"',
                "",
            ])
        
        # Performance Settings
        lines.extend([
            "# =============================================================================",
            "# PERFORMANCE SETTINGS",
            "# =============================================================================",
            "#",
            "# Application performance and scaling configuration",
            "#",
            "# WEB_CONCURRENCY: Number of web worker processes",
            "# Higher values improve concurrent user handling but use more memory",
            f'WEB_CONCURRENCY="{configuration.web_concurrency}"',
            "",
            "# WEB_TIMEOUT: Request timeout in seconds",
            f'WEB_TIMEOUT="{configuration.web_timeout}"',
            "",
            "# WEB_MAX_REQUESTS: Maximum requests per worker before restart",
            "# Helps prevent memory leaks in long-running processes",
            f'WEB_MAX_REQUESTS="{configuration.web_max_requests}"',
            "",
        ])
        
        # Security Settings
        lines.extend([
            "# =============================================================================",
            "# SECURITY SETTINGS",
            "# =============================================================================",
            "#",
            "# Security and encryption settings",
            "#",
            "# FORCE_SSL: Force all connections to use HTTPS",
            f'FORCE_SSL="{str(configuration.force_ssl).lower()}"',
            "",
            "# SESSION_COOKIE_SECURE: Mark session cookies as secure (HTTPS only)",
            f'SESSION_COOKIE_SECURE="{str(configuration.session_cookie_secure).lower()}"',
            "",
        ])
        
        # Feature Configuration
        lines.extend([
            "# =============================================================================",
            "# FEATURE CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Feature-specific settings",
            "#",
            "# ATTACHMENTS_STORAGE: Storage backend for file attachments",
            "# Options: file (local storage), fog (cloud storage)",
            f'ATTACHMENTS_STORAGE="{configuration.attachments_storage}"',
            "",
        ])
        
        # Logging Configuration
        lines.extend([
            "# =============================================================================",
            "# LOGGING CONFIGURATION",
            "# =============================================================================",
            "#",
            "# Application logging settings",
            "#",
            "# LOG_LEVEL: Logging verbosity level",
            "# Options: debug (most verbose), info, warn, error (least verbose)",
            f'LOG_LEVEL="{configuration.log_level}"',
            "",
            "# RAILS_LOG_TO_STDOUT: Output logs to stdout (recommended for containers)",
            f'RAILS_LOG_TO_STDOUT="{str(configuration.rails_log_to_stdout).lower()}"',
            "",
        ])
        
        # Custom Variables
        if configuration.custom_variables:
            lines.extend([
                "# =============================================================================",
                "# CUSTOM VARIABLES",
                "# =============================================================================",
                "#",
                "# Additional custom environment variables",
                "#",
            ])
            
            for key, value in configuration.custom_variables.items():
                lines.extend([
                    f"# {key}: Custom variable",
                    f'{key}="{value}"',
                    "",
                ])
        
        # Footer
        lines.extend([
            "# =============================================================================",
            "# END OF CONFIGURATION",
            "# =============================================================================",
            "#",
            "# This file is ready for use with the OpenProject deployment manager.",
            "# To deploy your OpenProject instance, run:",
            "#   deploy-manager --config interactive_config.cfg",
            "#",
            f"# Configuration generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ])
        
        return '\n'.join(lines)
    
    def write_docker_compose_env(self, 
                                configuration: Configuration,
                                output_path: Union[str, Path]) -> str:
        """
        Write configuration as Docker Compose .env file.
        
        Args:
            configuration: Configuration object to export
            output_path: Path to write the .env file
            
        Returns:
            Path to the written .env file
        """
        output_path = Path(output_path)
        
        logger.info(f"Writing Docker Compose .env file to {output_path}")
        
        # Create directory if it doesn't exist
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        lines = []
        
        # Header
        lines.extend([
            "# Docker Compose Environment File",
            "# Generated by OpenProject Configuration Manager",
            f"# Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "#",
            "# This file is used by docker-compose.yml to configure the OpenProject deployment",
            "",
        ])
        
        # Convert configuration to environment variables
        env_vars = self._configuration_to_env_vars(configuration)
        
        for key, value in env_vars.items():
            lines.append(f"{key}={value}")
        
        lines.append("")  # Final newline
        
        # Write to file
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write('\n'.join(lines))
            
            logger.info(f"Docker Compose .env file successfully written to {output_path}")
            
            # Set appropriate file permissions
            os.chmod(output_path, 0o640)
            
            return str(output_path)
            
        except Exception as e:
            logger.error(f"Failed to write .env file: {e}")
            raise
    
    def _configuration_to_env_vars(self, configuration: Configuration) -> dict:
        """Convert Configuration object to environment variables dictionary."""
        env_vars = {}
        
        # Core settings
        env_vars['SECRET_KEY_BASE'] = configuration.secret_key_base
        env_vars['RAILS_ENV'] = configuration.rails_env
        env_vars['RAILS_CACHE_STORE'] = configuration.rails_cache_store
        
        # Database settings
        env_vars['DATABASE_ADAPTER'] = configuration.database.adapter
        env_vars['DATABASE_HOST'] = configuration.database.host
        env_vars['DATABASE_PORT'] = str(configuration.database.port)
        env_vars['DATABASE_NAME'] = configuration.database.name
        env_vars['DATABASE_USERNAME'] = configuration.database.username
        env_vars['DATABASE_PASSWORD'] = configuration.database.password
        env_vars['DATABASE_ENCODING'] = configuration.database.encoding
        
        # Proxy settings
        env_vars['DOMAIN'] = configuration.proxy.domain
        if configuration.proxy.additional_domains:
            env_vars['ADDITIONAL_DOMAINS'] = ','.join(configuration.proxy.additional_domains)
        env_vars['SSL_ENABLED'] = str(configuration.proxy.ssl_enabled).lower()
        env_vars['LETS_ENCRYPT'] = str(configuration.proxy.lets_encrypt).lower()
        if configuration.proxy.lets_encrypt_email:
            env_vars['LETS_ENCRYPT_EMAIL'] = configuration.proxy.lets_encrypt_email
        if configuration.proxy.ssl_cert_path:
            env_vars['SSL_CERT_PATH'] = configuration.proxy.ssl_cert_path
        if configuration.proxy.ssl_key_path:
            env_vars['SSL_KEY_PATH'] = configuration.proxy.ssl_key_path
        
        # Storage settings
        env_vars['DATA_VOLUME'] = configuration.storage.data_volume
        env_vars['LOGS_VOLUME'] = configuration.storage.logs_volume
        env_vars['BACKUP_ENABLED'] = str(configuration.storage.backup_enabled).lower()
        env_vars['BACKUP_SCHEDULE'] = configuration.storage.backup_schedule
        env_vars['BACKUP_RETENTION_DAYS'] = str(configuration.storage.backup_retention_days)
        env_vars['BACKUP_LOCATION'] = configuration.storage.backup_location
        
        # Email settings
        env_vars['EMAIL_DELIVERY_METHOD'] = configuration.email_delivery_method
        if configuration.smtp_address:
            env_vars['SMTP_ADDRESS'] = configuration.smtp_address
        if configuration.smtp_port:
            env_vars['SMTP_PORT'] = str(configuration.smtp_port)
        if configuration.smtp_domain:
            env_vars['SMTP_DOMAIN'] = configuration.smtp_domain
        if configuration.smtp_user_name:
            env_vars['SMTP_USER_NAME'] = configuration.smtp_user_name
        if configuration.smtp_password:
            env_vars['SMTP_PASSWORD'] = configuration.smtp_password
        env_vars['SMTP_ENABLE_STARTTLS_AUTO'] = str(configuration.smtp_enable_starttls_auto).lower()
        
        # Cache settings
        env_vars['MEMCACHED_SERVER'] = configuration.memcached_server
        if configuration.redis_url:
            env_vars['REDIS_URL'] = configuration.redis_url
        
        # Performance settings
        env_vars['WEB_CONCURRENCY'] = str(configuration.web_concurrency)
        env_vars['WEB_TIMEOUT'] = str(configuration.web_timeout)
        env_vars['WEB_MAX_REQUESTS'] = str(configuration.web_max_requests)
        
        # Security settings
        env_vars['FORCE_SSL'] = str(configuration.force_ssl).lower()
        env_vars['SESSION_COOKIE_SECURE'] = str(configuration.session_cookie_secure).lower()
        
        # Feature settings
        env_vars['ATTACHMENTS_STORAGE'] = configuration.attachments_storage
        
        # Logging settings
        env_vars['LOG_LEVEL'] = configuration.log_level
        env_vars['RAILS_LOG_TO_STDOUT'] = str(configuration.rails_log_to_stdout).lower()
        
        # Custom variables
        env_vars.update(configuration.custom_variables)
        
        return env_vars