"""
Phase: TUI Defaults Mapping
Transform rich enhanced defaults to simple TUI format

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import sys

# === GENERATED: STEP_IMPORTS - DO NOT EDIT ===
# Handle both relative imports (when called by parent) and absolute imports (when run standalone)
if __name__ == '__main__':
    # Running standalone - use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_2_tui_mapping.step_1_transform_defaults.transform_defaults import TransformDefaultsStep
else:
    # When imported as module, use relative imports
    from .step_1_transform_defaults.transform_defaults import TransformDefaultsStep
# === END GENERATED: STEP_IMPORTS ===

# Infrastructure imports (preserved, not regenerated)
# Add phase-specific infrastructure imports here:
# - PathResolver for artifact resolution
# - Custom utilities or helpers
# - External dependencies
#
# Example:
# try:
#     from control_flow_engine.runtime import PathResolver, PathResolutionError
# except ImportError:
#     PathResolver = None
#     PathResolutionError = Exception

logger = logging.getLogger(__name__)


class TuiMappingPhase:
    """
    TUI Defaults Mapping
    Status: IMPLEMENTED
    
    Transform rich enhanced defaults to simple TUI format
    
    Artifacts Consumed: enhanced_defaults_file, defaults_mapping_config
    Artifacts Produced: tui_defaults_file
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_2_tui_mapping"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute TUI Defaults Mapping.
        
        Args:
            context: Execution context with consumed artifacts:
                - enhanced_defaults_file: Path to enhanced defaults from Phase 1
                - enhanced_defaults: Enhanced defaults structure
            
        Returns:
            Dict with produced artifacts:
                - tui_defaults_file: Path to transformed defaults file
                - tui_defaults: Transformed defaults structure
        """
        if self.ui:
            self.ui.show_phase_header("TUI Defaults Mapping", "Transform rich enhanced defaults to simple TUI format")
        
        logger.info("Executing TUI Defaults Mapping")
        
        result = {'artifacts': {}}
        
        # === GENERATED: STEP_EXECUTION - DO NOT EDIT ===
# Step 1: Transform rich enhanced defaults to simple TUI-compatible format
        logger.info("Step 1: Transform rich enhanced defaults to simple TUI-compatible format")
        step_1 = TransformDefaultsStep(self.project_root, self.ui)
        step_result = step_1.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
# === END GENERATED: STEP_EXECUTION ===
        
        logger.info("TUI Defaults Mapping completed successfully")
        
        # Build result from collected artifacts
        return {
            'artifacts': result['artifacts'],
            'tui_defaults_file': context.get('tui_defaults_file'),
            'tui_defaults': context.get('tui_defaults'),
            'transformation_summary': context.get('transformation_summary', {})
        }


def main():
    """Standalone entry point for testing Phase 2: TUI Defaults Mapping."""
    import argparse
    import yaml
    
    parser = argparse.ArgumentParser(description="Phase 2: TUI Defaults Mapping")
    parser.add_argument('--enhanced-defaults', required=True, help='Path to enhanced_defaults.yml from Phase 1')
    parser.add_argument('--output-dir', help='Output directory', default=None)
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    phase_dir = Path(__file__).parent
    project_root = phase_dir.parent.parent  # Go up 2 levels: phase_2_tui_mapping -> phases -> config-manager
    
    try:
        # Initialize phase
        phase = TuiMappingPhase(project_root=project_root, ui=None)
        
        # Load enhanced defaults
        enhanced_defaults_path = Path(args.enhanced_defaults)
        if not enhanced_defaults_path.exists():
            print(f"❌ Enhanced defaults file not found: {enhanced_defaults_path}")
            return 1
        
        with open(enhanced_defaults_path, 'r') as f:
            enhanced_defaults = yaml.safe_load(f)
        
        # Build context
        context = {
            'enhanced_defaults_file': str(enhanced_defaults_path),
            'enhanced_defaults': enhanced_defaults
        }
        
        # Execute phase
        logger.info("Executing TUI Defaults Mapping Phase")
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        print("✅ PHASE 2 COMPLETE: TUI Defaults Mapping")
        print("=" * 70)
        print(f"\n📊 Phase Summary:")
        print(f"  • tui_defaults_file: {result.get('tui_defaults_file', 'N/A')}")
        
        if 'transformation_summary' in result:
            summary = result['transformation_summary']
            print(f"\n📝 Transformation Summary:")
            print(f"  • Total defaults: {summary.get('total_defaults', 0)}")
            print(f"  • Transformed: {summary.get('transformed', 0)}")
        
        print(f"\n✅ Ready for Phase 3: Collection")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Phase 2 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
