"""
Step: Export Env File
Export .env file with environment variables for deployment

Migrated from orchestrator_export.py::_export_env_file()
"""

from pathlib import Path
from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)


def execute_export_env_file(context: Dict[str, Any], phase_dir: Path) -> Dict[str, Any]:
    """
    Export .env file with environment variables.
    
    Args:
        context: Execution context containing:
            - validated_configuration: Validated config from Phase 4
            - user_configuration: User config from Phase 3
            - export_dir: Target directory for exports
            
    Returns:
        Dict with artifacts:
            - env_file: Path to generated .env file
    """
    logger.info("Executing Export Env File")
    
    # Get export directory from context or use default
    project_root = phase_dir.parent.parent
    export_dir = context.get('export_dir', project_root / "phases/outputs")
    export_dir = Path(export_dir)
    export_dir.mkdir(parents=True, exist_ok=True)
    
    output_file = export_dir / '.env'
    
    # Get configuration from context
    validated_config = context.get('validated_configuration', {})
    user_config = context.get('user_configuration', validated_config)
    
    # If user_config is a file path string, use validated_config
    if isinstance(user_config, str):
        logger.warning(f"user_configuration is a path: {user_config}, using validated_config")
        user_config = validated_config
    
    # Extract configuration sections
    project = user_config.get('project', {})
    admin = user_config.get('admin', {})
    database = user_config.get('database', {})
    email = user_config.get('email', {})
    network = user_config.get('network', {})
    storage = user_config.get('storage', {})
    
    # Build environment variables
    env_vars = {
        '# OpenProject Configuration': '',
        '# Generated by config-manager': '',
        '': '',
        '# Project Settings': '',
        'PROJECT_NAME': project.get('name', 'OpenProject'),
        'PROJECT_IDENTIFIER': project.get('identifier', 'openproject'),
        'PROJECT_LANGUAGE': project.get('language', 'en'),
        '# Admin User': '',
        'ADMIN_EMAIL': admin.get('email', 'admin@example.com'),
        'ADMIN_FIRST_NAME': admin.get('first_name', 'Admin'),
        'ADMIN_LAST_NAME': admin.get('last_name', 'User'),
        '# Network Settings': '',
        'OPENPROJECT_HOST__NAME': network.get('domain', 'openproject.local'),
        'OPENPROJECT_HTTPS': str(network.get('ssl_enabled', False)).lower(),
        'OPENPROJECT_PORT': str(network.get('port', 80)),
        '# Database Configuration': '',
        'POSTGRES_DB': database.get('database_name', 'openproject'),
        'POSTGRES_USER': database.get('username', 'openproject'),
        'POSTGRES_PASSWORD': database.get('password', 'password'),
        'DATABASE_URL': f"postgres://{database.get('username', 'openproject')}:{database.get('password', 'password')}@db:5432/{database.get('database_name', 'openproject')}"
    }
    
    # Add email settings if configured
    if email.get('enabled'):
        env_vars.update({
            '# Email Configuration': '',
            'EMAIL_DELIVERY_METHOD': email.get('smtp_server', 'smtp') if email.get('smtp_server') else 'mailhog',
            'SMTP_ADDRESS': email.get('smtp_server', 'mailhog'),
            'SMTP_PORT': str(email.get('smtp_port', 1025)),
            'SMTP_DOMAIN': network.get('domain', 'openproject.local'),
            'SMTP_USERNAME': email.get('smtp_username', ''),
            'SMTP_PASSWORD': email.get('smtp_password', '')
        })
    
    # Write .env file
    with open(output_file, 'w') as f:
        for key, value in env_vars.items():
            if key.startswith('#') or key == '':
                f.write(f"{key}\n")
            else:
                f.write(f"{key}={value}\n")
    
    logger.info(f"Exported .env file to {output_file}")
    
    return {
        'env_file': str(output_file)
    }


class ExportEnvFileStep:
    """Wrapper class for export_env_file step."""
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_5_export"
    
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute export_env_file step.
        
        Args:
            context: Execution context
            
        Returns:
            Dict with artifacts
        """
        # Call existing function
        result_data = execute_export_env_file(context, self.phase_dir)
        
        # Return in expected format
        return {
            "artifacts": result_data if isinstance(result_data, dict) else {"data": result_data}
        }
