#!/usr/bin/env python3
"""
Main Phases Orchestrator - Config Manager
Coordinates execution of all 5 phases in the configuration pipeline.
"""

from pathlib import Path
from typing import Dict, Any, Optional
import logging
import sys
import yaml

# PathResolver for dynamic artifact/unit resolution
try:
    from control_flow_engine.runtime import PathResolver, PathResolutionError
except ImportError:
    PathResolver = None
    PathResolutionError = None

"""All imports resolved via packages; no sys.path manipulation required."""

# ==============================================================================
# PHASE_IMPORTS_BEGIN - Auto-generated section - Do not edit manually
# This section is regenerated by orchestrator_regenerator.py
# ==============================================================================
from phases.phase_1_discovery.orchestrator_discovery import DiscoveryPhase
from phases.phase_2_tui_mapping.orchestrator_tui_mapping import TuiMappingPhase
from phases.phase_3_collection.orchestrator_collection import CollectionPhase
from phases.phase_4_validation.orchestrator_validation import ValidationPhase
from phases.phase_5_export.orchestrator_export import ExportPhase
# ==============================================================================
# PHASE_IMPORTS_END
# ==============================================================================

# Infrastructure imports (add PathResolver and other utilities as needed)
# from src.openproject_config_manager.utils.path_resolver import PathResolver

logger = logging.getLogger(__name__)


class PhasesOrchestrator:
    """
    Main orchestrator for all configuration phases.
    
    Coordinates the complete configuration pipeline:
    1. Discovery: Probe system and generate intelligent defaults
    2. TUI Mapping: Transform defaults for TUI consumption
    3. Collection: Interactive user configuration collection
    4. Validation: Validate configuration integrity
    5. Export: Generate final configuration files
    """
    
    def __init__(self, project_root: Path, ui=None, mode: str = 'hardcoded', 
                 spec_file: Optional[Path] = None, flow_spec: Optional[Dict[str, Any]] = None):
        """
        Initialize the phases orchestrator.
        
        Args:
            project_root: Root directory of the project
            ui: Optional UI interface for user interaction
            mode: Execution mode ('hardcoded' or 'dynamic')
            spec_file: Path to control_flows.yml (for dynamic mode)
            flow_spec: Pre-loaded flow specification (for dynamic mode)
        """
        self.project_root = project_root
        self.ui = ui
        self.mode = mode
        self.spec_file = spec_file or self.project_root / "design_specs/control_flows.yml"
        self.flow_spec = flow_spec
        self.phases_dir = project_root / "phases"
        
        # Initialize PathResolver
        if PathResolver:
            try:
                self.path_resolver = PathResolver.from_execution_context(__file__)
                logger.debug(f"PathResolver initialized: {self.path_resolver.get_project_root()}")
            except Exception as e:
                logger.warning(f"Could not initialize PathResolver: {e}")
                self.path_resolver = None
        else:
            self.path_resolver = None
        
        # Initialize phase orchestrators with mode parameter
        self.discovery_phase = DiscoveryPhase(project_root, ui, mode=mode)
        self.tui_mapping_phase = TuiMappingPhase(project_root, ui, mode=mode)
        self.collection_phase = CollectionPhase(project_root, ui, mode=mode)
        self.validation_phase = ValidationPhase(project_root, ui, mode=mode)
        self.export_phase = ExportPhase(project_root, ui, mode=mode)
        
        logger.info(f"Phases orchestrator initialized (mode: {mode})")
    
    def execute_all_phases(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute all phases in sequence.
        
        Supports two execution modes:
        1. hardcoded (default): Uses static phase execution
        2. dynamic: Reads phases from YAML control_flows.yml
        
        Args:
            context: Initial execution context (optional)
            
        Returns:
            Dict containing results from all phases
        """
        if self.mode == "dynamic":
            return self._execute_dynamic(context)
        else:
            return self._execute_hardcoded(context)
    
    def _execute_dynamic(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute phases using YAML specification (dynamic mode).
        
        Reads phases from flow_spec and executes them in YAML-specified order.
        """
        if context is None:
            context = {}
        
        # Load flow spec if not provided
        if not self.flow_spec:
            if self.spec_file and self.spec_file.exists():
                with open(self.spec_file, 'r') as f:
                    spec = yaml.safe_load(f)
                    # Get first flow (or default flow)
                    flows = spec.get('flows', {})
                    if isinstance(flows, dict):
                        self.flow_spec = next(iter(flows.values())) if flows else None
                    elif isinstance(flows, list):
                        self.flow_spec = flows[0] if flows else None
            
            if not self.flow_spec:
                logger.warning("No flow spec available, falling back to hardcoded mode")
                return self._execute_hardcoded(context)
        
        from datetime import datetime
        context['generated_at'] = datetime.now().isoformat()
        
        logger.info("=" * 80)
        logger.info("Starting YAML-driven configuration pipeline execution")
        logger.info("=" * 80)
        
        result = {'phases': {}}
        
        # Execute phases in YAML order
        for phase_spec in self.flow_spec.get('phases', []):
            phase_id = phase_spec['phase_id']
            phase_status = phase_spec.get('status', 'PLANNED')
            
            if phase_status in ['PLANNED', 'SKIPPED']:
                logger.info(f"Skipping phase {phase_id} (status: {phase_status})")
                continue
            
            logger.info(f"\n🔧 Executing phase: {phase_id}")
            logger.info("-" * 80)
            
            # Map phase_id to phase instance
            phase_instance = self._get_phase_by_id(phase_id)
            if phase_instance:
                phase_result = phase_instance.execute(context)
                context.update(phase_result)
                result['phases'][phase_id] = phase_result
                logger.info(f"✓ Phase {phase_id} complete")
            else:
                logger.error(f"Unknown phase: {phase_id}")
        
        logger.info("\n" + "=" * 80)
        logger.info("🎉 YAML-DRIVEN PIPELINE COMPLETE")
        logger.info("=" * 80)
        
        return {
            'pipeline_status': 'complete',
            'execution_mode': 'dynamic',
            'phases': result['phases'],
            'final_context': context
        }
    
    def _execute_hardcoded(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Hardcoded execution mode (original implementation).
        
        Execute all phases in fixed order with static logic.
        """
        if context is None:
            context = {}
        
        # Add generation timestamp
        from datetime import datetime
        context['generated_at'] = datetime.now().isoformat()
        
        logger.info("=" * 80)
        logger.info("Starting complete configuration pipeline execution")
        logger.info("=" * 80)
        
        try:
            # Phase 1: Discovery
            logger.info("\n📡 PHASE 1: DISCOVERY")
            logger.info("-" * 80)
            phase1_result = self.discovery_phase.execute(context)
            context.update(phase1_result)
            logger.info(f"✓ Phase 1 complete: {phase1_result.get('discovery_summary', {})}")
            
            # Phase 2: TUI Mapping
            logger.info("\n🔄 PHASE 2: TUI MAPPING")
            logger.info("-" * 80)
            phase2_result = self.tui_mapping_phase.execute(context)
            context.update(phase2_result)
            logger.info(f"✓ Phase 2 complete: {phase2_result.get('transformation_summary', {})}")
            
            # Phase 3: Collection
            logger.info("\n📝 PHASE 3: COLLECTION")
            logger.info("-" * 80)
            phase3_result = self.collection_phase.execute(context)
            context.update(phase3_result)
            logger.info(f"✓ Phase 3 complete: Configuration collected")
            
            # Phase 4: Validation
            logger.info("\n✅ PHASE 4: VALIDATION")
            logger.info("-" * 80)
            phase4_result = self.validation_phase.execute(context)
            context.update(phase4_result)
            
            validation_passed = phase4_result.get('validation_passed', False)
            if not validation_passed:
                logger.warning("⚠️  Validation warnings detected")
                if self.ui and not self.ui.confirm("Continue with export despite warnings?"):
                    raise ValueError("Pipeline aborted due to validation failures")
            else:
                logger.info("✓ Phase 4 complete: All validations passed")
            
            # Phase 5: Export
            logger.info("\n📤 PHASE 5: EXPORT")
            logger.info("-" * 80)
            phase5_result = self.export_phase.execute(context)
            context.update(phase5_result)
            logger.info(f"✓ Phase 5 complete: {phase5_result.get('export_summary', {})}")
            
            logger.info("\n" + "=" * 80)
            logger.info("🎉 PIPELINE COMPLETE - All phases executed successfully!")
            logger.info("=" * 80)
            
            return {
                'pipeline_status': 'complete',
                'phase_1_discovery': phase1_result,
                'phase_2_tui_mapping': phase2_result,
                'phase_3_collection': phase3_result,
                'phase_4_validation': phase4_result,
                'phase_5_export': phase5_result,
                'final_context': context
            }
            
        except Exception as e:
            logger.error(f"❌ Pipeline failed: {e}")
            raise
    
    def _get_phase_by_id(self, phase_id: str):
        """
        Get phase instance by phase_id.
        
        Args:
            phase_id: Phase identifier from YAML (e.g., 'discovery', 'collection')
            
        Returns:
            Phase orchestrator instance or None
        """
        phase_map = {
            'discovery': self.discovery_phase,
            'tui_mapping': self.tui_mapping_phase,
            'collection': self.collection_phase,
            'validation': self.validation_phase,
            'export': self.export_phase
        }
        return phase_map.get(phase_id)
    
    def execute_phase(self, phase_number: int, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute a single phase by number.
        
        Args:
            phase_number: Phase number (1-5)
            context: Execution context
            
        Returns:
            Dict containing phase results
        """
        phase_map = {
            1: ('Discovery', self.discovery_phase),
            2: ('TUI Mapping', self.tui_mapping_phase),
            3: ('Collection', self.collection_phase),
            4: ('Validation', self.validation_phase),
            5: ('Export', self.export_phase)
        }
        
        if phase_number not in phase_map:
            raise ValueError(f"Invalid phase number: {phase_number}. Must be 1-5.")
        
        phase_name, phase_instance = phase_map[phase_number]
        logger.info(f"Executing Phase {phase_number}: {phase_name}")
        
        result = phase_instance.execute(context)
        logger.info(f"Phase {phase_number} ({phase_name}) completed")
        
        return result
    
    def execute_phases_range(self, start_phase: int, end_phase: int, 
                           context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Execute a range of phases.
        
        Args:
            start_phase: Starting phase number (1-5)
            end_phase: Ending phase number (1-5)
            context: Initial execution context
            
        Returns:
            Dict containing results from executed phases
        """
        if context is None:
            context = {}
        
        if not (1 <= start_phase <= 5 and 1 <= end_phase <= 5):
            raise ValueError("Phase numbers must be between 1 and 5")
        
        if start_phase > end_phase:
            raise ValueError("start_phase must be <= end_phase")
        
        logger.info(f"Executing phases {start_phase} through {end_phase}")
        
        results = {}
        for phase_num in range(start_phase, end_phase + 1):
            phase_result = self.execute_phase(phase_num, context)
            context.update(phase_result)
            results[f'phase_{phase_num}'] = phase_result
        
        return {
            'phases_executed': list(range(start_phase, end_phase + 1)),
            'results': results,
            'final_context': context
        }


def create_orchestrator(project_root: Path, ui=None, mode: str = 'hardcoded') -> PhasesOrchestrator:
    """
    Factory function to create a phases orchestrator instance.
    
    Args:
        project_root: Root directory of the project
        ui: Optional UI interface
        mode: Execution mode ('hardcoded' or 'dynamic')
        
    Returns:
        Configured PhasesOrchestrator instance
    """
    return PhasesOrchestrator(project_root, ui, mode=mode)


def main():
    """Main entry point when run as a script."""
    import argparse
    
    # Setup logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    parser = argparse.ArgumentParser(
        description='Config Manager Phases Orchestrator',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Execute all phases
  python3 phases_orchestrator.py --all
  
  # Execute specific phase
  python3 phases_orchestrator.py --phase 1
  
  # Execute range of phases
  python3 phases_orchestrator.py --start 1 --end 2
  
  # Verbose output
  python3 phases_orchestrator.py --start 1 --end 2 --verbose

Note: You can also use run_phases.py from the project root for more options.
        """
    )
    
    parser.add_argument(
        '--all',
        action='store_true',
        help='Execute all 5 phases in sequence'
    )
    
    parser.add_argument(
        '--phase',
        type=int,
        choices=[1, 2, 3, 4, 5],
        help='Execute a single phase (1-5)'
    )
    
    parser.add_argument(
        '--start',
        type=int,
        choices=[1, 2, 3, 4, 5],
        help='Start phase for range execution (use with --end)'
    )
    
    parser.add_argument(
        '--end',
        type=int,
        choices=[1, 2, 3, 4, 5],
        help='End phase for range execution (use with --start)'
    )
    
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Enable verbose logging'
    )
    
    parser.add_argument(
        '--dynamic',
        action='store_true',
        help='Use YAML-driven execution mode (read phases from control_flows.yml)'
    )
    
    args = parser.parse_args()
    
    # Set logging level
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)
    
    # Get project root (parent of phases directory)
    project_root = Path(__file__).parent.parent
    
    # Create orchestrator with mode
    mode = 'dynamic' if args.dynamic else 'hardcoded'
    orchestrator = create_orchestrator(project_root, mode=mode)
    
    try:
        if args.all:
            logger.info("Executing all phases...")
            result = orchestrator.execute_all_phases()
            logger.info("✅ All phases completed successfully!")
            return 0
            
        elif args.phase:
            logger.info(f"Executing Phase {args.phase}...")
            context = {}
            result = orchestrator.execute_phase(args.phase, context)
            logger.info(f"✅ Phase {args.phase} completed successfully!")
            return 0
            
        elif args.start and args.end:
            logger.info(f"Executing Phases {args.start}-{args.end}...")
            result = orchestrator.execute_phases_range(args.start, args.end)
            logger.info(f"✅ Phases {args.start}-{args.end} completed successfully!")
            return 0
            
        else:
            # Default: Execute all phases (migration complete!)
            logger.info("Executing all phases (1-5)...")
            logger.info("Use --help to see all execution options")
            result = orchestrator.execute_all_phases()
            logger.info("✅ All phases completed successfully!")
            return 0
            
    except Exception as e:
        logger.error(f"❌ Execution failed: {e}", exc_info=args.verbose)
        return 1


if __name__ == '__main__':
    sys.exit(main())
