"""
Phase: Discovery Phase
Discover system environment and generate intelligent defaults

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import sys

# === GENERATED: STEP_IMPORTS - DO NOT EDIT ===
# Handle both relative imports (when called by parent) and absolute imports (when run standalone)
if __name__ == '__main__':
    # Running standalone - use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_1_discovery.step_0_discovery_prompt.discovery_prompt import DiscoveryPromptStep
    from phases.phase_1_discovery.step_1_env_discovery.env_discovery import EnvDiscoveryStep
    from phases.phase_1_discovery.step_2_system_discovery.system_discovery import SystemDiscoveryStep
    from phases.phase_1_discovery.step_3_defaults_generation.defaults_generation import DefaultsGenerationStep
else:
    # When imported as module, use relative imports
    from .step_0_discovery_prompt.discovery_prompt import DiscoveryPromptStep
    from .step_1_env_discovery.env_discovery import EnvDiscoveryStep
    from .step_2_system_discovery.system_discovery import SystemDiscoveryStep
    from .step_3_defaults_generation.defaults_generation import DefaultsGenerationStep
# === END GENERATED: STEP_IMPORTS ===

# Infrastructure imports (preserved, not regenerated)
# Add phase-specific infrastructure imports here:
# - PathResolver for artifact resolution
# - Custom utilities or helpers
# - External dependencies
#
# Example:
# try:
#     from control_flow_engine.runtime import PathResolver, PathResolutionError
# except ImportError:
#     PathResolver = None
#     PathResolutionError = Exception

logger = logging.getLogger(__name__)


class DiscoveryPhase:
    """
    Discovery Phase
    Status: IMPLEMENTED
    
    Discover system environment and generate intelligent defaults
    
    Artifacts Consumed: None
    Artifacts Produced: enhanced_defaults_file
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_1_discovery"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Discovery Phase.
        
        Args:
            context: Execution context with consumed artifacts
            
        Returns:
            Dict with produced artifacts
        """
        if self.ui:
            self.ui.show_phase_header("Discovery Phase", "Discover system environment and generate intelligent defaults")
        
        logger.info("Executing Discovery Phase")
        
        result = {'artifacts': {}}
        
        # === GENERATED: STEP_EXECUTION - DO NOT EDIT ===
# Step 1: Ask user whether to use automatic system discovery or manual configuration
        logger.info("Step 1: Ask user whether to use automatic system discovery or manual configuration")
        step_1 = DiscoveryPromptStep(self.project_root, self.ui)
        step_result = step_1.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 2: Discover environment variables and system paths
        logger.info("Step 2: Discover environment variables and system paths")
        step_2 = EnvDiscoveryStep(self.project_root, self.ui)
        step_result = step_2.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 3: Discover system information, Docker, and network configuration
        logger.info("Step 3: Discover system information, Docker, and network configuration")
        step_3 = SystemDiscoveryStep(self.project_root, self.ui)
        step_result = step_3.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
        # Step 4: Generate enhanced defaults from discovered system information
        logger.info("Step 4: Generate enhanced defaults from discovered system information")
        step_4 = DefaultsGenerationStep(self.project_root, self.ui)
        step_result = step_4.execute(context)
        context.update(step_result.get("artifacts", {}))
        result["artifacts"].update(step_result.get("artifacts", {}))
        
# === END GENERATED: STEP_EXECUTION ===
        
        # Build result from collected artifacts
        return {
            'artifacts': result['artifacts'],
            'enhanced_defaults_file': context.get('enhanced_defaults_file'),
            'enhanced_defaults': context.get('enhanced_defaults'),
            'environment_data': context.get('environment_data'),
            'system_data': context.get('system_data'),
            'docker_data': context.get('docker_data'),
            'network_data': context.get('network_data'),
            'discovery_summary': {
                'environment_variables': len(context.get('environment_data', {}).get('all_vars', {})),
                'system_info': 'collected' if context.get('system_data') else 'not collected',
                'docker_info': 'collected' if context.get('docker_data') else 'unavailable',
                'network_info': 'collected' if context.get('network_data') else 'not collected',
                'defaults_generated': len(context.get('enhanced_defaults', {}))
            }
        }


def main():
    """Standalone entry point for testing Phase 1."""
    import argparse
    import sys
    
    parser = argparse.ArgumentParser(description="Phase 1: Discovery Phase")
    parser.add_argument('--output-dir', help='Output directory for results', default='phases/phase_1_discovery/outputs')
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    project_root = Path(__file__).parent.parent.parent
    
    # Create phase instance
    phase = DiscoveryPhase(project_root=project_root)
    
    try:
        # Execute phase with empty context
        context = {}
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        print("✅ PHASE 1 COMPLETE: Discovery")
        print("=" * 70)
        print(f"\n📊 Discovery Summary:")
        for key, value in result['discovery_summary'].items():
            print(f"  • {key}: {value}")
        print(f"\n📁 Enhanced defaults saved to:")
        print(f"  {result['enhanced_defaults_file']}")
        print("\n✅ Ready for Phase 2: TUI Mapping")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Phase 1 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
