"""
Phase: Discovery Phase
Discover system environment and generate intelligent defaults

Generated by Control Flow Engine
"""

from pathlib import Path
from typing import Dict, Any
import logging
import sys

# Handle both relative imports (when called by parent) and absolute imports (when run standalone)
if __name__ == '__main__':
    # Running standalone - use absolute imports
    sys.path.insert(0, str(Path(__file__).parent.parent.parent))
    from phases.phase_1_discovery.step_1_env_discovery import env_discovery
    from phases.phase_1_discovery.step_2_system_discovery import system_discovery
    from phases.phase_1_discovery.step_3_defaults_generation import defaults_generation
else:
    # Running as module - use relative imports
    from .step_1_env_discovery import env_discovery
    from .step_2_system_discovery import system_discovery
    from .step_3_defaults_generation import defaults_generation

logger = logging.getLogger(__name__)


class DiscoveryPhase:
    """
    Discovery Phase
    Status: IMPLEMENTED
    
    Discover system environment and generate intelligent defaults
    
    Artifacts Consumed: None
    Artifacts Produced: enhanced_defaults_file
    """
    
    def __init__(self, project_root: Path, ui=None):
        self.project_root = project_root
        self.ui = ui
        self.phase_dir = project_root / "phases/phase_1_discovery"
        
    def execute(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute Discovery Phase.
        
        Args:
            context: Execution context with consumed artifacts
            
        Returns:
            Dict with produced artifacts
        """
        if self.ui:
            self.ui.show_phase_header("Discovery Phase", "Discover system environment and generate intelligent defaults")
        
        logger.info("Executing Discovery Phase")
        
        # Step 1: Environment Discovery
        logger.info("Step 1/3: Environment Discovery")
        env_result = env_discovery.execute_env_discovery(context, self.phase_dir)
        context['environment_data'] = env_result
        
        # Step 2: System Discovery
        logger.info("Step 2/3: System Discovery")
        system_result = system_discovery.execute_system_discovery(context, self.phase_dir)
        context['system_data'] = system_result.get('system_data', {})
        context['docker_data'] = system_result.get('docker_data', {})
        context['network_data'] = system_result.get('network_data', {})
        
        # Step 3: Defaults Generation
        logger.info("Step 3/3: Intelligent Defaults Generation")
        defaults_result = defaults_generation.execute_defaults_generation(context, self.phase_dir)
        
        logger.info("Discovery Phase completed successfully")
        
        return {
            'enhanced_defaults_file': defaults_result['enhanced_defaults_file'],
            'enhanced_defaults': defaults_result['enhanced_defaults'],
            'discovery_summary': {
                'environment_variables': len(context['environment_data'].get('all_vars', {})),
                'system_info': 'collected',
                'docker_info': 'collected' if context['docker_data'] else 'unavailable',
                'network_info': 'collected',
                'defaults_generated': defaults_result['defaults_summary']['total_defaults_generated']
            }
        }


def main():
    """Standalone entry point for testing Phase 1."""
    import argparse
    import sys
    
    parser = argparse.ArgumentParser(description="Phase 1: Discovery Phase")
    parser.add_argument('--output-dir', help='Output directory for results', default='phases/phase_1_discovery/outputs')
    parser.add_argument('--verbose', action='store_true', help='Enable verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Setup paths
    project_root = Path(__file__).parent.parent.parent
    
    # Create phase instance
    phase = DiscoveryPhase(project_root=project_root)
    
    try:
        # Execute phase with empty context
        context = {}
        result = phase.execute(context)
        
        print("\n" + "=" * 70)
        print("✅ PHASE 1 COMPLETE: Discovery")
        print("=" * 70)
        print(f"\n📊 Discovery Summary:")
        for key, value in result['discovery_summary'].items():
            print(f"  • {key}: {value}")
        print(f"\n📁 Enhanced defaults saved to:")
        print(f"  {result['enhanced_defaults_file']}")
        print("\n✅ Ready for Phase 2: TUI Mapping")
        
        return 0
        
    except Exception as e:
        print(f"\n❌ Phase 1 failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == '__main__':
    exit(main())
