"""Tests for configuration export functionality."""

import pytest
import os
from pathlib import Path
from unittest.mock import patch, Mock
from datetime import datetime

from openproject_config_manager.export.cfg_writer import CfgWriter
from openproject_config_manager.core.config import Configuration


class TestCfgWriter:
    """Test CfgWriter class."""
    
    def test_init(self):
        """Test CfgWriter initialization."""
        writer = CfgWriter()
        assert writer is not None
    
    def test_write_configuration_basic(self, sample_configuration, temp_dir):
        """Test basic configuration writing."""
        writer = CfgWriter()
        output_path = temp_dir / "test_config.cfg"
        
        result_path = writer.write_configuration(
            sample_configuration, 
            output_path,
            backup_existing=False,
            add_comments=False
        )
        
        # Check that file was created
        assert Path(result_path).exists()
        assert result_path == str(output_path)
        
        # Check file content
        content = output_path.read_text(encoding='utf-8')
        assert 'SECRET_KEY_BASE=' in content
        assert 'DATABASE_ADAPTER=' in content
        assert 'DOMAIN=' in content
    
    def test_write_configuration_with_comments(self, sample_configuration, temp_dir):
        """Test configuration writing with comments."""
        writer = CfgWriter()
        output_path = temp_dir / "test_config.cfg"
        
        result_path = writer.write_configuration(
            sample_configuration, 
            output_path,
            add_comments=True
        )
        
        # Check that file was created
        assert Path(result_path).exists()
        
        # Check file content includes comments
        content = output_path.read_text(encoding='utf-8')
        assert '# OpenProject Configuration File' in content
        assert '# Generated by OpenProject Configuration Manager' in content
        assert '# CORE OPENPROJECT SETTINGS' in content
        assert '# DATABASE CONFIGURATION' in content
        assert '# SECRET_KEY_BASE: Used for encrypting' in content
    
    def test_write_configuration_backup_existing(self, sample_configuration, temp_dir):
        """Test configuration writing with backup of existing file."""
        writer = CfgWriter()
        output_path = temp_dir / "test_config.cfg"
        
        # Create existing file
        existing_content = "# Existing configuration"
        output_path.write_text(existing_content, encoding='utf-8')
        
        with patch('shutil.copy2') as mock_copy:
            result_path = writer.write_configuration(
                sample_configuration, 
                output_path,
                backup_existing=True
            )
        
        # Check that backup was attempted
        mock_copy.assert_called_once()
        
        # Check that new file was written
        assert Path(result_path).exists()
        content = output_path.read_text(encoding='utf-8')
        assert existing_content not in content
        assert 'SECRET_KEY_BASE=' in content
    
    def test_write_configuration_create_directory(self, sample_configuration, temp_dir):
        """Test configuration writing creates directory if needed."""
        writer = CfgWriter()
        output_path = temp_dir / "subdir" / "test_config.cfg"
        
        # Directory should not exist initially
        assert not output_path.parent.exists()
        
        result_path = writer.write_configuration(
            sample_configuration, 
            output_path
        )
        
        # Directory should be created
        assert output_path.parent.exists()
        assert Path(result_path).exists()
    
    def test_write_configuration_file_permissions(self, sample_configuration, temp_dir):
        """Test that configuration file gets correct permissions."""
        writer = CfgWriter()
        output_path = temp_dir / "test_config.cfg"
        
        with patch('os.chmod') as mock_chmod:
            writer.write_configuration(sample_configuration, output_path)
        
        # Check that chmod was called with correct permissions (0o640)
        mock_chmod.assert_called_once_with(output_path, 0o640)
    
    def test_backup_existing_file(self, temp_dir):
        """Test backup of existing file."""
        writer = CfgWriter()
        original_file = temp_dir / "config.cfg"
        original_content = "# Original content"
        original_file.write_text(original_content, encoding='utf-8')
        
        with patch('shutil.copy2') as mock_copy:
            writer._backup_existing_file(original_file)
        
        # Should call copy2 with source and backup path
        mock_copy.assert_called_once()
        args = mock_copy.call_args[0]
        assert args[0] == original_file
        assert str(args[1]).endswith('.bak')
    
    def test_backup_existing_file_exception(self, temp_dir):
        """Test backup with exception handling."""
        writer = CfgWriter()
        original_file = temp_dir / "config.cfg"
        original_file.write_text("content", encoding='utf-8')
        
        with patch('shutil.copy2', side_effect=Exception("Backup failed")):
            # Should not raise exception, just log warning
            writer._backup_existing_file(original_file)
    
    def test_generate_cfg_with_comments_complete(self, sample_configuration):
        """Test complete .cfg generation with comments."""
        writer = CfgWriter()
        
        content = writer._generate_cfg_with_comments(sample_configuration)
        
        # Check header
        assert "# OpenProject Configuration File" in content
        assert "# Generated by OpenProject Configuration Manager" in content
        
        # Check sections
        assert "# CORE OPENPROJECT SETTINGS" in content
        assert "# DATABASE CONFIGURATION" in content
        assert "# PROXY AND SECURITY CONFIGURATION" in content
        assert "# STORAGE AND BACKUP CONFIGURATION" in content
        assert "# EMAIL CONFIGURATION" in content
        assert "# PERFORMANCE SETTINGS" in content
        assert "# SECURITY SETTINGS" in content
        
        # Check specific values
        assert f'SECRET_KEY_BASE="{sample_configuration.secret_key_base}"' in content
        assert f'DATABASE_ADAPTER="{sample_configuration.database.adapter}"' in content
        assert f'DOMAIN="{sample_configuration.proxy.domain}"' in content
        
        # Check custom variables section
        if sample_configuration.custom_variables:
            assert "# CUSTOM VARIABLES" in content
            for key, value in sample_configuration.custom_variables.items():
                assert f'{key}="{value}"' in content
    
    def test_generate_cfg_with_comments_ssl_settings(self):
        """Test .cfg generation with SSL settings."""
        config = Configuration(
            secret_key_base="a" * 64,
            proxy={
                "domain": "example.com",
                "ssl_enabled": True,
                "lets_encrypt": False,
                "ssl_cert_path": "/path/to/cert.pem",
                "ssl_key_path": "/path/to/key.pem"
            }
        )
        
        writer = CfgWriter()
        content = writer._generate_cfg_with_comments(config)
        
        assert 'SSL_ENABLED="true"' in content
        assert 'SSL_CERT_PATH="/path/to/cert.pem"' in content
        assert 'SSL_KEY_PATH="/path/to/key.pem"' in content
    
    def test_generate_cfg_with_comments_backup_disabled(self):
        """Test .cfg generation with backup disabled."""
        config = Configuration(
            secret_key_base="a" * 64,
            proxy={"domain": "example.com"},
            storage={"backup_enabled": False}
        )
        
        writer = CfgWriter()
        content = writer._generate_cfg_with_comments(config)
        
        assert 'BACKUP_ENABLED="false"' in content
        # Backup-specific settings should not be present
        assert 'BACKUP_SCHEDULE=' not in content
        assert 'BACKUP_RETENTION_DAYS=' not in content
        assert 'BACKUP_LOCATION=' not in content
    
    def test_write_docker_compose_env(self, sample_configuration, temp_dir):
        """Test writing Docker Compose .env file."""
        writer = CfgWriter()
        output_path = temp_dir / "test.env"
        
        result_path = writer.write_docker_compose_env(sample_configuration, output_path)
        
        # Check that file was created
        assert Path(result_path).exists()
        assert result_path == str(output_path)
        
        # Check file content
        content = output_path.read_text(encoding='utf-8')
        assert 'SECRET_KEY_BASE=' in content
        assert 'DATABASE_ADAPTER=' in content
        assert 'DOMAIN=' in content
        
        # Should not have quotes around values in .env format
        lines = content.split('\n')
        env_lines = [line for line in lines if '=' in line and not line.startswith('#')]
        
        # Check that values are not quoted (Docker Compose .env format)
        for line in env_lines:
            if '=' in line:
                key, value = line.split('=', 1)
                # Values should not be wrapped in quotes
                assert not (value.startswith('"') and value.endswith('"'))
    
    def test_write_docker_compose_env_permissions(self, sample_configuration, temp_dir):
        """Test Docker Compose .env file permissions."""
        writer = CfgWriter()
        output_path = temp_dir / "test.env"
        
        with patch('os.chmod') as mock_chmod:
            writer.write_docker_compose_env(sample_configuration, output_path)
        
        # Check that chmod was called with correct permissions (0o640)
        mock_chmod.assert_called_once_with(output_path, 0o640)
    
    def test_configuration_to_env_vars(self, sample_configuration):
        """Test conversion of configuration to environment variables."""
        writer = CfgWriter()
        
        env_vars = writer._configuration_to_env_vars(sample_configuration)
        
        # Check core variables
        assert env_vars['SECRET_KEY_BASE'] == sample_configuration.secret_key_base
        assert env_vars['RAILS_ENV'] == sample_configuration.rails_env
        assert env_vars['DATABASE_ADAPTER'] == sample_configuration.database.adapter
        
        # Check port conversion to string
        assert env_vars['DATABASE_PORT'] == str(sample_configuration.database.port)
        
        # Check boolean conversion to lowercase string
        assert env_vars['SSL_ENABLED'] == str(sample_configuration.proxy.ssl_enabled).lower()
        assert env_vars['BACKUP_ENABLED'] == str(sample_configuration.storage.backup_enabled).lower()
        
        # Check array conversion
        if sample_configuration.proxy.additional_domains:
            assert env_vars['ADDITIONAL_DOMAINS'] == ','.join(sample_configuration.proxy.additional_domains)
        
        # Check custom variables
        if sample_configuration.custom_variables:
            for key, value in sample_configuration.custom_variables.items():
                assert env_vars[key] == value
    
    def test_configuration_to_env_vars_optional_fields(self):
        """Test environment variable conversion with optional fields."""
        config = Configuration(
            secret_key_base="a" * 64,
            proxy={"domain": "example.com"},
            # Most optional fields are None/empty
        )
        
        writer = CfgWriter()
        env_vars = writer._configuration_to_env_vars(config)
        
        # Required fields should be present
        assert 'SECRET_KEY_BASE' in env_vars
        assert 'DOMAIN' in env_vars
        
        # Optional fields should only be present if they have values
        assert 'SMTP_ADDRESS' not in env_vars or env_vars['SMTP_ADDRESS'] == ''
        assert 'REDIS_URL' not in env_vars or env_vars['REDIS_URL'] == ''
    
    def test_write_configuration_exception_handling(self, sample_configuration, temp_dir):
        """Test exception handling during file writing."""
        writer = CfgWriter()
        
        # Use a path that will cause a permission error
        with patch('builtins.open', side_effect=PermissionError("Permission denied")):
            with pytest.raises(PermissionError):
                writer.write_configuration(sample_configuration, temp_dir / "test.cfg")
    
    def test_configuration_export_roundtrip(self, sample_configuration, temp_dir):
        """Test that configuration can be exported and re-imported."""
        writer = CfgWriter()
        cfg_file = temp_dir / "roundtrip.cfg"
        
        # Export configuration
        writer.write_configuration(
            sample_configuration, 
            cfg_file,
            add_comments=False  # Comments might interfere with parsing
        )
        
        # Re-import configuration
        imported_config = Configuration.from_cfg_file(cfg_file)
        
        # Compare key fields
        assert imported_config.secret_key_base == sample_configuration.secret_key_base
        assert imported_config.rails_env == sample_configuration.rails_env
        assert imported_config.database.adapter == sample_configuration.database.adapter
        assert imported_config.database.host == sample_configuration.database.host
        assert imported_config.database.port == sample_configuration.database.port
        assert imported_config.proxy.domain == sample_configuration.proxy.domain
        assert imported_config.proxy.ssl_enabled == sample_configuration.proxy.ssl_enabled